"use client";
import ProfileComponent from "@/components/User/Profile";
import { Metadata } from "next";

// export const metadata: Metadata = {
//     title: "Login Amlak",
//     description: "Generated by create next app",
// };

export default function User() {
  return (
    <ProfileComponent>
      <div className="p-6">
        <h1 className="text-xl font-bold mb-4">حساب کاربری</h1>
        <p className="text-gray-600">اطلاعات حساب کاربری شما</p>
      </div>
    </ProfileComponent>
  );
}
