"use client";
import ProfileComponent from "@/components/User/Profile";
import { Metadata } from "next";

// export const metadata: Metadata = {
//     title: "Login Amlak",
//     description: "Generated by create next app",
// };

export default function User() {
    return <ProfileComponent />;
}

