// import { Metadata } from "next";
import ChatComponent from "@/components/Chat";
// export const metadata: Metadata = {
//     title: "Login Amlak",
//     description: "Generated by create next app",
// };

export default function Chat() {
  return <ChatComponent />;
}
